Data Cleaning and Preparing
===========================

<a id="1"></a>
1: Index
---------

- [1: Index](#1)
- [2: Types of Bad Data](#2)
- [3: Exploring a Dataset](#3)

<a id="2"></a>
2: Types of Bad Data
--------------------

- Formatting errors (e.g. extra whitespace)
- Value errors (e.g., misspellings) (note according to Treehouse, misspellings are classified
  as "Formatting errors")
- Incorrect data type (e.g. numerical or string entries)
- Nonsensical data entries (e.g. age < 0)
- Duplicate entries (duplicate rows or columns)
- Missing data (e.g. NaN)
- Saturated data (e.g. value beyond a measurement limit)
- Systematic and individual errors (error affects many entries or only one)
- Confidential information (e.g. personally identifying or private information)

<a id="3"> </a>
3: Exploring a Dataset
----------------------

- [3.0: Setup](#3.0)
- [3.1: Exploring a Subset](#3.1)

<a id="3.0"> </a>
### 3.0: Setup ###

In [1]:
import os
import numpy as np
import pandas as pd

DATAPATH = os.path.join('thirdpartydata', 'cleaning-preparing-s1v4')

bodymeasures_filename = os.path.join(DATAPATH, 'BodyMeasures.csv')
demographics_filename = os.path.join(DATAPATH, 'Demographics.csv')
occupations_filename = os.path.join(DATAPATH, 'Occupations.csv')

In [2]:
# codebook URL: https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/BMX.htm
bodymeasures = pd.read_csv(bodymeasures_filename)
bodymeasures.head()

SEQN  BMAEXLEN  BMAEXSTS  BMAEXCMT  BMXWT  BMIWT  BMXRECUM  BMIRECUM  \
0     1     289.0       1.0       NaN   12.5    3.0      93.2       NaN   
1     2     376.0       1.0       NaN   75.4    NaN       NaN       NaN   
2     3     199.0       1.0       NaN   32.9    NaN       NaN       NaN   
3     4     170.0       1.0       NaN   13.3    NaN      87.1       NaN   
4     5     277.0       1.0       NaN   92.5    NaN       NaN       NaN   

   BMXHEAD  BMIHEAD  ...  BMAAMP  BMAUREXT  BMAUPREL  BMAULEXT  BMAUPLEL  \
0      NaN      NaN  ...     2.0       NaN       NaN       NaN       NaN   
1      NaN      NaN  ...     2.0       NaN       NaN       NaN       NaN   
2      NaN      NaN  ...     2.0       NaN       NaN       NaN       NaN   
3      NaN      NaN  ...     2.0       NaN       NaN       NaN       NaN   
4      NaN      NaN  ...     2.0       NaN       NaN       NaN       NaN   

   BMALOREX  BMALORKN  BMALLEXT  BMALLKNE  RIDAGEYR  
0       NaN       NaN       NaN       NaN         2  
1       NaN       NaN       NaN       NaN        77  
2       NaN       NaN       NaN       NaN        95  
3       NaN       NaN       NaN       NaN         1  
4       NaN       NaN       NaN       NaN        49  

[5 rows x 39 columns]

In [3]:
bodymeasures.describe()

SEQN     BMAEXLEN     BMAEXSTS    BMAEXCMT         BMXWT  \
count  9278.000000  9266.000000  9266.000000  138.000000   9181.000000   
mean   4992.804592   261.712066     1.021368   25.905797     67.519987   
std    2869.638216    80.976300     0.183440   37.109207    282.449524   
min       1.000000     0.000000     1.000000    1.000000   -149.000000   
25%    2517.250000   211.000000     1.000000    2.000000     39.200000   
50%    4988.500000   258.000000     1.000000    6.000000     63.000000   
75%    7482.750000   307.000000     1.000000   56.000000     79.700000   
max    9965.000000   909.000000     3.000000   99.000000  12870.000000   

            BMIWT     BMXRECUM  BMIRECUM     BMXHEAD  BMIHEAD  ...  \
count  253.000000  1079.000000      29.0  267.000000      1.0  ...   
mean     2.976285    80.244486       1.0   41.319476      1.0  ...   
std      1.174899    13.927584       0.0    2.980247      NaN  ...   
min      1.000000    44.900000       1.0   15.500000      1.0  ...   
25%      3.000000    69.150000       1.0   39.500000      1.0  ...   
50%      3.000000    81.300000       1.0   41.700000      1.0  ...   
75%      3.000000    91.800000       1.0   43.150000      1.0  ...   
max     11.000000   110.300000       1.0   47.900000      1.0  ...   

            BMAAMP  BMAUREXT  BMAUPREL  BMAULEXT  BMAUPLEL  BMALOREX  \
count  9148.000000       3.0       0.0       3.0       0.0       3.0   
mean      1.999672       2.0       NaN       2.0       NaN       1.0   
std       0.018107       0.0       NaN       0.0       NaN       0.0   
min       1.000000       2.0       NaN       2.0       NaN       1.0   
25%       2.000000       2.0       NaN       2.0       NaN       1.0   
50%       2.000000       2.0       NaN       2.0       NaN       1.0   
75%       2.000000       2.0       NaN       2.0       NaN       1.0   
max       2.000000       2.0       NaN       2.0       NaN       1.0   

       BMALORKN  BMALLEXT  BMALLKNE     RIDAGEYR  
count       3.0  3.000000       1.0  9278.000000  
mean        2.0  1.666667       2.0    29.014766  
std         0.0  0.577350       NaN    24.442185  
min         2.0  1.000000       2.0   -69.000000  
25%         2.0  1.500000       2.0    10.000000  
50%         2.0  2.000000       2.0    19.000000  
75%         2.0  2.000000       2.0    47.000000  
max         2.0  2.000000       2.0   109.000000  

[8 rows x 39 columns]

In [4]:
# codebook URL: https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/DEMO.htm
demographics = pd.read_csv(demographics_filename)
demographics.head()

SEQN  SDDSRVYR RIDSTATR  RIDEXMON RIAGENDR  RIDAGEYR  RIDAGEMN  RIDAGEEX  \
0     1       1.0   Exam         2.0   Female       2.0      29.0      31.0   
1     2       1.0   Both         2.0     Male      77.0     926.0     926.0   
2     3       1.0     Exam       1.0   Female      95.0     125.0     126.0   
3     4       1.0     Both       2.0     Male       1.0      22.0      23.0   
4     5       1.0    Both        2.0     Male      49.0     597.0     597.0   

               RIDRETH1  RIDRETH2  ...      WTIREP43      WTIREP44  \
0    Non-Hispanic Black       2.0  ...  10094.017100   9912.461855   
1    Non-Hispanic White       1.0  ...  27186.728682  27324.345051   
2    Non-Hispanic White       1.0  ...  43993.193099  44075.386428   
3    Non-Hispanic Black       2.0  ...  10702.307249  10531.444441   
4    Non-Hispanic White       1.0  ...  93164.782430  92119.608772   

       WTIREP45      WTIREP46      WTIREP47      WTIREP48      WTIREP49  \
0   9727.078709  10041.524113   9953.955984   9857.381983   9865.152486   
1  28099.663528  27757.066921  28049.286048  26716.602006  26877.704909   
2  46642.563799  44967.681579  44572.482010  44087.945688  44831.370881   
3  10346.119327  10636.063039      0.000000  10533.108939  10654.749584   
4  95388.490406  94131.383538  95297.809952  91325.082461  91640.586117   

       WTIREP50      WTIREP51      WTIREP52  
0  10327.992682   9809.165049  10323.315747  
1  27268.025234  27406.383620  26984.812909  
2  44480.987235  45389.112766  43781.905637  
3  10851.024385  10564.981435  11012.529729  
4  92817.926915  94282.855382  91993.251203  

[5 rows x 144 columns]

In [5]:
# codebook URL: https://wwwn.cdc.gov/Nchs/Nhanes/1999-2000/OCQ.htm
occupations = pd.read_csv(occupations_filename)
occupations.head()

SEQN  OCQ130  OCQ150  OCQ160  OCQ180  OCQ210  OCD230  OCD240  OCQ260  \
0   2.0     NaN     2.0     2.0     NaN     1.0    38.0    13.0     1.0   
1   5.0     NaN     1.0     NaN    40.0     NaN    19.0     1.0     1.0   
2   6.0     NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
3   7.0     NaN     1.0     NaN    45.0     NaN    27.0    23.0     1.0   
4   8.0     7.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

   OCD270  ...  OCD390  OCD395  OCQ420  OCQ430  OCQ440  OCQ450  OCQ470G  \
0   168.0  ...     9.0   300.0     NaN     NaN     NaN     NaN      NaN   
1    48.0  ...     NaN     NaN     NaN     NaN     NaN     NaN      NaN   
2     NaN  ...    16.0     3.0     2.0     NaN     NaN     NaN      NaN   
3    36.0  ...     NaN     NaN     NaN     NaN     NaN     NaN      NaN   
4     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN      NaN   

   OCD470  OCD480  RIAGENDR  
0     NaN     NaN      Male  
1     NaN     NaN      Male  
2     NaN     NaN    Female  
3     NaN     NaN       F    
4     NaN     NaN         M  

[5 rows x 37 columns]

In [6]:
# Make a dataset by joining demographics and bodymeasurements
dataset = pd.merge(demographics, bodymeasures, on='SEQN', how='inner') # CF 7.2 in the Pandas Notebook
dataset.head()

SEQN  SDDSRVYR RIDSTATR  RIDEXMON RIAGENDR  RIDAGEYR_x  RIDAGEMN  RIDAGEEX  \
0     1       1.0   Exam         2.0   Female         2.0      29.0      31.0   
1     2       1.0   Both         2.0     Male        77.0     926.0     926.0   
2     3       1.0     Exam       1.0   Female        95.0     125.0     126.0   
3     4       1.0     Both       2.0     Male         1.0      22.0      23.0   
4     5       1.0    Both        2.0     Male        49.0     597.0     597.0   

               RIDRETH1  RIDRETH2  ... BMAAMP BMAUREXT BMAUPREL BMAULEXT  \
0    Non-Hispanic Black       2.0  ...    2.0      NaN      NaN      NaN   
1    Non-Hispanic White       1.0  ...    2.0      NaN      NaN      NaN   
2    Non-Hispanic White       1.0  ...    2.0      NaN      NaN      NaN   
3    Non-Hispanic Black       2.0  ...    2.0      NaN      NaN      NaN   
4    Non-Hispanic White       1.0  ...    2.0      NaN      NaN      NaN   

  BMAUPLEL BMALOREX  BMALORKN BMALLEXT BMALLKNE  RIDAGEYR_y  
0      NaN      NaN       NaN      NaN      NaN           2  
1      NaN      NaN       NaN      NaN      NaN          77  
2      NaN      NaN       NaN      NaN      NaN          95  
3      NaN      NaN       NaN      NaN      NaN           1  
4      NaN      NaN       NaN      NaN      NaN          49  

[5 rows x 182 columns]

In [7]:
# Write the dataset back out as a CSV
#dataset.to_csv('joined_demo_bmx.csv', index=False)

<a id="3.1"> </a>
### 3.1: Exploring a Subset ###

- [3.1.1: Browse Data and Rename Columns](#3.1.1)
- [3.1.2: Clean Globally](#3.1.2)
- [3.1.3: Clean Military](#3.1.3)
- [3.1.4: Clean Citizenship](#3.1.4)
- [3.1.5: Clean Gender](#3.1.5)
- [3.1.6: Save CSV](#3.1.6)

<a id="3.1.1"> </a>
#### 3.1.1: Browse Data and Rename Columns ####

In [8]:
# 'SEQN' = ID
# 'RIDAGEYR' = Age at Screening (should be capped at 85)
# 'RIAGENDR' = Gender
# 'DMQMILIT' = Veteran/Military Status
# 'DMDCITZN' = Citizenship Status
demo_subset = demographics.loc[:, ['SEQN', 'RIDAGEYR', 'RIAGENDR', 'DMQMILIT', 'DMDCITZN']]
demo_subset.rename(columns={'SEQN': 'ID', 'RIDAGEYR': 'Age', 'RIAGENDR': 'Gender', 'DMQMILIT': 'Military', 'DMDCITZN': 'Citizenship'}, inplace=True)
demo_subset.head()

ID   Age  Gender Military                         Citizenship
0   1   2.0  Female      NaN  Citizen by birth or naturalization
1   2  77.0    Male        Y  Citizen by birth or naturalization
2   3  95.0  Female      NaN             Not a citizen of the US
3   4   1.0    Male      NaN  Citizen by birth or naturalization
4   5  49.0    Male      Yes  Citizen by birth or naturalization

<a id="3.1.2"> </a>
#### 3.1.2: Clean Globally ####

In [9]:
# Instead of cleaning whitespace on each column individually (original code left as comments 
# below), we can use the apply method to clean all relevant columns in one go:
text_columns = ['Gender', 'Military', 'Citizenship']
demo_subset[text_columns] = demo_subset[text_columns].apply(lambda x: x.str.strip())


# We can fix minor typos like 'Y' -> 'Yes', etc
BINARY_CORRECTION_MAP = {
    'Y': 'Yes',
    'N': 'No',
}
GENDER_CORRECTION_MAP = {
    'M': 'Male',
    'F': 'Female',
}
DONTKNOW_CORRECTION_MAP = {
    "Don't Know": "Don't know",
    "Dont know": "Don't know",
    "Unknown": "Don't know",
}

global_replacements = {
    **BINARY_CORRECTION_MAP,
    **GENDER_CORRECTION_MAP,
    **DONTKNOW_CORRECTION_MAP,
}

demo_subset.replace(
    {
        'Military': {**global_replacements},
        'Citizenship': {**global_replacements},
        'Gender': {**global_replacements},
    },
    inplace=True
)

<a id="3.1.3"> </a>
#### 3.1.3: Clean Military ####

In [10]:
unique_military = demo_subset['Military'].unique()
len(unique_military)

5

In [11]:
# 38 seems like a lot of unique values for military status
unique_military

array([nan, 'Yes', 'No', "Don't know", 'Refused'], dtype=object)

In [12]:
# we can see lots of duplicates (and many just have extraneous whitespace)
#demo_subset.loc[:, 'Military'] = demo_subset.loc[:, 'Military'].str.strip()

In [13]:
unique_military = demo_subset['Military'].unique()
len(unique_military)

5

In [14]:
unique_military

array([nan, 'Yes', 'No', "Don't know", 'Refused'], dtype=object)

In [15]:
#replace_dict = {'Military': {**BINARY_CORRECTION_MAP, **DONTKNOW_CORRECTION_MAP}}
#demo_subset.replace(replace_dict, inplace=True)

In [16]:
unique_military = demo_subset['Military'].unique()
len(unique_military)

5

In [17]:
# Success: We are down to the 5 truly different response values
unique_military

array([nan, 'Yes', 'No', "Don't know", 'Refused'], dtype=object)

In [18]:
# Replace unique string values with numeric codes:
replace_dict = {
    'Military': {
        'Yes': 1,
        'No': 2,
        'Refused': 7,
        "Don't know": 9,
    }
}
demo_subset.replace(replace_dict, inplace=True)
unique_military = demo_subset['Military'].unique()
unique_military

array([nan,  1.,  2.,  9.,  7.])

<a id="3.1.4"> </a>
#### 3.1.4: Clean Citizenship ####

In [19]:
# Let's repeat for citizenship (we'll strip whitespace before we even look at the values
#demo_subset.loc[:,'Citizenship'] = demo_subset.loc[:, 'Citizenship'].str.strip()
unique_citizenship = demo_subset['Citizenship'].unique()
unique_citizenship

array(['Citizen by birth or naturalization', 'Not a citizen of the US',
       'Refused', "Don't know", nan], dtype=object)

In [20]:
#replace_dict = {'Citizenship': {**DONTKNOW_CORRECTION_MAP}}
#demo_subset.replace(replace_dict, inplace=True)

In [21]:
unique_citizenship = demo_subset['Citizenship'].unique()
unique_citizenship

array(['Citizen by birth or naturalization', 'Not a citizen of the US',
       'Refused', "Don't know", nan], dtype=object)

In [22]:
# Replace unique string values with numeric codes:
replace_dict = {
    'Citizenship': {
        'Citizen by birth or naturalization': 1,
        'Not a citizen of the US': 2,
        'Refused': 7,
        "Don't know": 9,
    }
}
demo_subset.replace(replace_dict, inplace=True)
unique_citizenship = demo_subset['Citizenship'].unique()
unique_citizenship

array([ 1.,  2.,  7.,  9., nan])

<a id="3.1.5"> </a>
#### 3.1.5: Clean Gender ####

In [23]:
#demo_subset.loc[:, 'Gender'] = demo_subset.loc[:, 'Gender'].str.strip()
unique_gender = demo_subset['Gender'].unique()
unique_gender

array(['Female', 'Male', nan], dtype=object)

In [24]:
#replace_dict = {'Gender': {**GENDER_CORRECTION_MAP}}
#demo_subset.replace(replace_dict, inplace=True)

In [25]:
unique_gender = demo_subset['Gender'].unique()
unique_gender

array(['Female', 'Male', nan], dtype=object)

In [26]:
# Replace unique string values with numeric codes:
replace_dict = {
    'Gender': {
        'Male': 1,
        'Female': 2,
    }
}
demo_subset.replace(replace_dict, inplace=True)
unique_gender = demo_subset['Gender'].unique()
unique_gender

array([ 2.,  1., nan])

<a id="3.1.6"> </a>
#### 3.1.6: Save CSV ####

In [27]:
#demo_subset.to_csv('demo_subset.csv', index=False)